'use client'

import { useEffect, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { createCourse, inviteAcademyMember, sendNotification, updateProfile, updateCourseStatus, updateUserRole } from '@/app/actions/academy'

type Props = { user: any; courses: any[]; notifications: any[]; profiles: any[]; lessons: any[]; assessments: any[]; enrollments: any[]; forumPosts: any[] }

export function AdminPortal({ user, courses, notifications, profiles, lessons, assessments, enrollments, forumPosts }: Props) {
  const router = useRouter()
  const [section, setSection] = useState('dashboard')
  const [pending, startTransition] = useTransition()
  const [message, setMessage] = useState('')
  useEffect(() => { const handle = (event: Event) => setSection((event as CustomEvent<string>).detail || 'dashboard'); window.addEventListener('portal:navigate', handle); return () => window.removeEventListener('portal:navigate', handle) }, [])
  const run = (action: () => Promise<unknown>) => startTransition(async () => { setMessage(''); try { await action(); setMessage('Saved successfully.'); router.refresh() } catch (error) { setMessage(error instanceof Error ? error.message : 'Request failed.') } })
  const stats = [['Total users', profiles.length], ['Courses', courses.length], ['Published', courses.filter((c) => c.status === 'published').length], ['Notifications', notifications.length]]
  return <div className="space-y-8">
    {message && <p role="status" className="rounded-xl border border-primary/30 bg-primary/10 px-4 py-3 text-sm text-primary">{message}</p>}
    {section === 'dashboard' && <div className="space-y-8"><div><p className="text-sm font-semibold uppercase tracking-widest text-primary">Academy operations</p><h2 className="mt-2 text-3xl font-bold">Good morning, {user.name}</h2><p className="mt-2 text-muted-foreground">Manage people, learning content, communications, and platform health.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([label, value]) => <div key={String(label)} className="rounded-xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><AdminPanel title="Recent courses"><div className="space-y-3">{courses.slice(0, 6).map((course) => <div key={course.id} className="flex items-center justify-between rounded-lg border border-border/70 p-3"><span className="text-sm font-medium">{course.title}</span><select value={course.status} onChange={(e) => run(() => updateCourseStatus({ courseId: course.id, status: e.target.value as 'draft' | 'published' | 'archived' }))} disabled={pending} className="rounded-lg border border-border bg-background px-2 py-1 text-xs capitalize"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div>)}{!courses.length && <Empty text="No courses created yet." />}</div></AdminPanel><AdminPanel title="Operations checklist"><div className="space-y-3 text-sm text-muted-foreground"><p>Review new learner access requests.</p><p>Publish or update current course content.</p><p>Check announcements and notification delivery.</p><p>Review instructor activity and assessments.</p></div></AdminPanel></div></div>}
    {section === 'users' && <UserManagement profiles={profiles} run={run} pending={pending} onBack={() => setSection('dashboard')} />}
    {section === 'courses' && <CourseManagement courses={courses} run={run} pending={pending} onBack={() => setSection('dashboard')} />}
    {section === 'announcements' && <AnnouncementManagement profiles={profiles} run={run} pending={pending} onBack={() => setSection('dashboard')} />}
    {section === 'settings' && <SettingsManagement user={user} run={run} pending={pending} onBack={() => setSection('dashboard')} />}
    {section === 'analytics' && <AdminAnalytics courses={courses} profiles={profiles} lessons={lessons} enrollments={enrollments} forumPosts={forumPosts} onBack={() => setSection('dashboard')} />}
    {section === 'lessons' && <AdminContent title="Lessons" items={lessons} courses={courses} kind="lesson" onBack={() => setSection('dashboard')} />}
    {section === 'assessments' && <AdminContent title="Assessments" items={assessments} courses={courses} lessons={lessons} kind="assessment" onBack={() => setSection('dashboard')} />}
    {section === 'pricing' && <AdminPricing courses={courses} run={run} pending={pending} onBack={() => setSection('dashboard')} />}
  </div>
}

function UserManagement({ profiles, run, pending, onBack }: any) { const [email, setEmail] = useState(''); const [role, setRole] = useState<'student' | 'instructor'>('student'); return <div className="space-y-6"><Back onBack={onBack} /><div><h2 className="text-2xl font-bold">Users & roles</h2><p className="mt-1 text-muted-foreground">Invite and monitor academy accounts.</p></div><AdminPanel title="Invite member"><div className="flex flex-col gap-3 md:flex-row"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="recipient@example.com" className="flex-1 rounded-lg border border-border bg-background px-4 py-2" /><select value={role} onChange={(e) => setRole(e.target.value as any)} className="rounded-lg border border-border bg-background px-4 py-2"><option value="student">Student</option><option value="instructor">Instructor</option></select><button disabled={pending || !email} onClick={() => run(() => inviteAcademyMember({ email, role }))} className="rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground disabled:opacity-50">Send invite</button></div></AdminPanel><AdminPanel title="Registered profiles"><div className="space-y-2">{profiles.map((profile: any) => <div key={profile.id} className="flex items-center justify-between rounded-lg border border-border/70 p-3"><span className="text-sm font-medium">{profile.displayName || profile.id}</span><div className="flex items-center gap-2"><select value={profile.role} onChange={(e) => run(() => updateUserRole({ userId: profile.id, role: e.target.value as 'student' | 'instructor' | 'admin' }))} disabled={pending} className="rounded-lg border border-border bg-background px-2 py-1 text-xs capitalize"><option value="student">Student</option><option value="instructor">Instructor</option><option value="admin">Admin</option></select></div></div>)}{!profiles.length && <Empty text="No profiles yet." />}</div></AdminPanel></div> }
function CourseManagement({ courses, run, pending, onBack }: any) { const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [description, setDescription] = useState(''); return <div className="space-y-6"><Back onBack={onBack} /><div><h2 className="text-2xl font-bold">Course management</h2><p className="mt-1 text-muted-foreground">Create, organize, and oversee the academy catalog.</p></div><AdminPanel title="Create course"><div className="grid gap-3 md:grid-cols-3"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Course title" className="rounded-lg border border-border bg-background px-4 py-2" /><input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="course-slug" className="rounded-lg border border-border bg-background px-4 py-2" /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Short description" className="rounded-lg border border-border bg-background px-4 py-2" /></div><button disabled={pending || !title || !slug} onClick={() => run(() => createCourse({ title, slug, description }))} className="mt-4 rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground disabled:opacity-50">Create course</button></AdminPanel><AdminPanel title="Catalog"><div className="space-y-2">{courses.map((course: any) => <div key={course.id} className="flex items-center justify-between rounded-lg border border-border/70 p-3"><span className="text-sm font-medium">{course.title}</span><select value={course.status} onChange={(e) => run(() => updateCourseStatus({ courseId: course.id, status: e.target.value as 'draft' | 'published' | 'archived' }))} disabled={pending} className="rounded-lg border border-border bg-background px-2 py-1 text-xs capitalize"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div>)}{!courses.length && <Empty text="No courses yet." />}</div></AdminPanel></div> }
function AnnouncementManagement({ profiles, run, pending, onBack }: any) { const [recipientId, setRecipientId] = useState(''); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); return <div className="space-y-6"><Back onBack={onBack} /><AdminPanel title="Send announcement"><select value={recipientId} onChange={(e) => setRecipientId(e.target.value)} className="w-full rounded-lg border border-border bg-background px-4 py-2"><option value="">Select recipient</option>{profiles.map((profile: any) => <option key={profile.id} value={profile.id}>{profile.displayName || profile.id}</option>)}</select><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Announcement title" className="w-full rounded-lg border border-border bg-background px-4 py-2" /><textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder="Message" className="min-h-24 w-full rounded-lg border border-border bg-background px-4 py-2" /><button disabled={pending || !recipientId || !title || !body} onClick={() => run(() => sendNotification({ recipientId, title, body }))} className="rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground disabled:opacity-50">Send announcement</button></AdminPanel></div> }
function SettingsManagement({ user, run, pending, onBack }: any) { const [name, setName] = useState(user.name); return <div className="space-y-6"><Back onBack={onBack} /><AdminPanel title="Admin settings"><p className="text-sm text-muted-foreground">{user.email}</p><input value={name} onChange={(e) => setName(e.target.value)} className="w-full rounded-lg border border-border bg-background px-4 py-2" /><button disabled={pending || !name} onClick={() => run(() => updateProfile({ displayName: name }))} className="rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground disabled:opacity-50">Save settings</button></AdminPanel></div> }
function AdminAnalytics({ courses, profiles, lessons, enrollments, forumPosts, onBack }: any) { return <div className="space-y-6"><Back onBack={onBack} /><div><h2 className="text-2xl font-bold">Platform analytics</h2><p className="mt-1 text-muted-foreground">A live operational view of academy health.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Users', profiles.length], ['Courses', courses.length], ['Lessons', lessons.length], ['Enrollments', enrollments.length]].map(([label, value]) => <div key={label as string} className="rounded-xl border border-border bg-card p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</div><AdminPanel title="Recent discussion activity"><p className="text-sm text-muted-foreground">{forumPosts.length ? `${forumPosts.length} discussion posts are available for moderation.` : 'No discussion posts yet.'}</p></AdminPanel></div> }
function AdminContent({ title, items, courses = [], lessons = [], kind, onBack }: any) { return <div className="space-y-6"><Back onBack={onBack} /><div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-muted-foreground">Review live learning content across the academy.</p></div><AdminPanel title={`${items.length} ${kind}s`}><div className="space-y-3">{items.map((item: any) => <div key={item.id} className="rounded-lg border border-border/70 p-4"><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{kind === 'lesson' ? courses.find((course: any) => course.id === item.courseId)?.title || 'Course' : `${lessons.find((lesson: any) => lesson.id === item.lessonId)?.title || 'Lesson'} · ${item.type}`}</p></div>)}{!items.length && <Empty text={`No ${kind}s have been created yet.`} />}</div></AdminPanel></div> }
function AdminPricing({ courses, run, pending, onBack }: any) { return <div className="space-y-6"><Back onBack={onBack} /><div><h2 className="text-2xl font-bold">Pricing operations</h2><p className="mt-1 text-muted-foreground">Review catalog pricing before publishing.</p></div><AdminPanel title="Course pricing"><div className="space-y-3">{courses.map((course: any) => <div key={course.id} className="flex items-center justify-between rounded-lg border border-border/70 p-4"><div><p className="font-medium">{course.title}</p><p className="text-sm text-muted-foreground">{course.priceCents ? `BWP ${(course.priceCents / 100).toFixed(2)}` : 'Free course'}</p></div><span className="text-xs capitalize text-muted-foreground">{course.status}</span></div>)}{!courses.length && <Empty text="No courses to price yet." />}</div></AdminPanel></div> }

function AdminPanel({ title, children }: any) { return <section className="rounded-xl border border-border bg-card p-6"><h3 className="font-semibold">{title}</h3><div className="mt-4 space-y-3">{children}</div></section> }
function Back({ onBack }: any) { return <button onClick={onBack} className="text-sm text-muted-foreground hover:text-foreground">← Back to dashboard</button> }
function Empty({ text }: { text: string }) { return <p className="text-sm text-muted-foreground">{text}</p> }
